import { AppConfig } from "@/types/apps";

export const APPS: AppConfig[] = [
  {
    id: "finder",
    name: "Finder",
    icon: "/finder.png",
    description: "File browser",
    accentColor: "#007AFF",
    defaultPosition: { x: 80, y: 40 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Finder",
    multiWindow: true,
    cascadeOffset: 30,
  },
  {
    id: "messages",
    name: "Messages",
    icon: "/messages.png",
    description: "Chat with AI personas",
    accentColor: "#34C759",
    defaultPosition: { x: 150, y: 80 },
    defaultSize: { width: 800, height: 550 },
    minSize: { width: 500, height: 400 },
    menuBarTitle: "Messages",
  },
  {
    id: "music",
    name: "Spotify",
    icon: "/spotify1.webp",
    iconScale: 1.35,
    description: "Music streaming",
    accentColor: "#1DB954",
    defaultPosition: { x: 140, y: 70 },
    defaultSize: { width: 900, height: 650 },
    minSize: { width: 600, height: 450 },
    menuBarTitle: "Spotify",
  },
  {
    id: "calendar",
    name: "Calendar",
    icon: "/calendar.png",
    description: "Calendar and events",
    accentColor: "#FF3B30",
    defaultPosition: { x: 170, y: 60 },
    defaultSize: { width: 900, height: 700 },
    minSize: { width: 700, height: 500 },
    menuBarTitle: "Calendar",
  },
  {
    id: "weather",
    name: "Weather",
    icon: "/weather.png",
    description: "Weather forecast",
    accentColor: "#0A7CFF",
    defaultPosition: { x: 220, y: 90 },
    defaultSize: { width: 780, height: 560 },
    minSize: { width: 560, height: 420 },
    menuBarTitle: "Weather",
    showOnDockByDefault: false,
    mobile: {
      supported: false,
      shellFallbackAppId: "messages",
      directRouteRedirectTo: "/",
      showInFinderApplications: false,
    },
  },
  {
    id: "iterm",
    name: "iTerm",
    icon: "/iterm.png",
    description: "Terminal emulator",
    accentColor: "#00D455",
    defaultPosition: { x: 120, y: 70 },
    defaultSize: { width: 800, height: 500 },
    minSize: { width: 500, height: 300 },
    menuBarTitle: "iTerm",
  },
  {
    id: "settings",
    name: "Settings",
    icon: "/settings.png",
    description: "System preferences",
    accentColor: "#8E8E93",
    defaultPosition: { x: 200, y: 100 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 700, height: 400 },
    menuBarTitle: "System Settings",
  },
  {
    id: "textedit",
    name: "TextEdit",
    icon: "/textedit.png",
    description: "Plain text editor",
    accentColor: "#8E8E93",
    defaultPosition: { x: 160, y: 90 },
    defaultSize: { width: 700, height: 500 },
    minSize: { width: 400, height: 300 },
    menuBarTitle: "TextEdit",
    showOnDockByDefault: false,
    mobile: {
      supported: false,
      shellFallbackAppId: "finder",
      directRouteRedirectTo: "/",
      showInFinderApplications: false,
    },
    multiWindow: true,
    cascadeOffset: 30,
  },
  {
    id: "preview",
    name: "Preview",
    icon: "/preview.png",
    description: "Image and PDF viewer",
    accentColor: "#007AFF",
    defaultPosition: { x: 180, y: 100 },
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 400, height: 300 },
    menuBarTitle: "Preview",
    showOnDockByDefault: false,
    mobile: {
      supported: false,
      shellFallbackAppId: "finder",
      directRouteRedirectTo: "/",
      showInFinderApplications: false,
    },
    multiWindow: true,
    cascadeOffset: 30,
  },
  {
    id: "canvas",
    name: "Canvas",
    icon: "/canvas.svg",
    iconScale: 0.85,
    description: "Collaborative drawing canvas",
    accentColor: "#FF3B30",
    defaultPosition: { x: 160, y: 80 },
    defaultSize: { width: 900, height: 650 },
    minSize: { width: 500, height: 400 },
    menuBarTitle: "Canvas",
  },
  {
    id: "safari",
    name: "Safari",
    icon: "/safari.png",
    iconScale: 1.3,
    description: "Web browser",
    accentColor: "#007AFF",
    defaultPosition: { x: 120, y: 60 },
    defaultSize: { width: 1100, height: 750 },
    minSize: { width: 600, height: 450 },
    menuBarTitle: "Safari",
  },
  {
    id: "disney",
    name: "Disney+",
    icon: "/disney.png",
    iconScale: 0.85,
    description: "Stream movies and series",
    accentColor: "#0E47CC",
    defaultPosition: { x: 140, y: 70 },
    defaultSize: { width: 1200, height: 780 },
    minSize: { width: 700, height: 500 },
    menuBarTitle: "Disney+",
  },
];

export function getAppById(id: string): AppConfig | undefined {
  return APPS.find((app) => app.id === id);
}

export function getAppIds(): string[] {
  return APPS.map((app) => app.id);
}
